spring:
  application:
    name: user-microservice
  amqp:
    deserialization:
      trust:
        all: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
server:
  port: 8081
